postgres: &postgres
  adapter: postgresql
  host: localhost
  min_messages: WARNING

development:
  <<: *postgres
  database: elements_db

test:
  <<: *postgres
  database: elements_db_test

production:
  <<: *postgres
  database: elements_db
